---
# -*- coding: utf-8 -*-

language: python
sudo: required
cache: pip
python:
  - "3.6"
services:
  - docker

install:
  - pip install --upgrade ansible ansible-lint ansible-test yamllint

before_script:
  - git clone https://github.com/adfinis-sygroup/ansible-lint-rules ../lint-rules
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - ERRORS=0

script:
  - ansible-lint -R -r ../lint-rules . || let ERRORS+=1 ;
  - yamllint -c .testenv/yamllint.yml "$dir" || let ERRORS+=1 ;
  - if [ $ERRORS -ne 0 ]; then exit $ERRORS; fi
  - ansible-test --image debian:9 . || let ERRORS+=1
  - ansible-test --image debian:8 . || let ERRORS+=1
  - ansible-test --image debian:7 . || let ERRORS+=1
  - ansible-test --image ubuntu:16 . || let ERRORS+=1
  - ansible-test --image ubuntu:14 . || let ERRORS+=1
  - ansible-test --image centos:7 . || let ERRORS+=1
  - ansible-test --image centos:6 . || let ERRORS+=1
  - exit $ERRORS

notifications:
  webhooks:
    - 'https://galaxy.ansible.com/api/v1/notifications/'

# vim: set ts=2 sw=2 tw=2 :
